DROP DATABASE IF EXISTS workplace_db;
CREATE DATABASE workplace_db;

USE workplace_db;

--DEPARTMENT TABLE
--ROLE TABLE
--EMPLOYEE TABLE

DROP TABLE IF EXISTS department;
CREATE TABLE department ( --DEPARTMENT TABLE
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
  name VARCHAR(30) NOT NULL, --HOLD DEPARTMENT NAME
);

DROP TABLE IF EXISTS role;
CREATE TABLE role ( --ROLE TABLE
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
  title VARCHAR(30) NOT NULL, --HOLD ROLE TITLE
  salary DECIMAL NOT NULL, -- SALARY ROLE
  department_id INT, --HOLD REFERENCE TO DEPARTMENT ROLE BELONGS TO
  FOREIGN KEY department_id, 
  REFERENCES department(id),
  ON DELETE SET NULL,
);

DROP TABLE IF EXISTS employee;
CREATE TABLE employee ( --ROLE TABLE
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
  first_name VARCHAR(30) NOT NULL, --HOLD EMPLOYEE FIRST NAME
  last_name VARCHAR(30) NOT NULL, --HOLD EMPLOYEE LAST NAME
  role_id INT, --HOLD REFERENCE TO EMPLOYEE ROLE
  manager_id INT, --HOLD REFERENCE TO ANOTHER EMPLOYEE THAT IS THE MANAGER OF THE CURRENT EMPLOYEE [NULL IF THE EMPLOYEE HAS NO MANAGER]
  FOREIGN KEY role_id,
  REFERENCES role(id),
  FOREIGN KEY manager_id, 
  REFERENCES employee(id),
  ON DELETE SET NULL,
);